version: "3.7"

services:
  short:
    build:
      args:
        user: webuser
        uid: 1000
      context: ./docker/php
      dockerfile: Dockerfile
    image: short_image
    container_name: short-app
#    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./docker/upload.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks:
      - short_net

  nginx:
    image: nginx:alpine
    container_name: short-nginx
#    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - short_net

  db:
    image: mysql:5.7
    container_name: db-short
    #    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker/mysql/db:/var/lib/mysql
      - ./docker/mysql/dump:/docker-entrypoint-initdb.d
    networks:
      - short_net

  redis:
    image: redis:latest
    container_name: short-redis
    ports:
      - "6379:6379"
    networks:
      - short_net

  memcached:
    container_name: short-memcached
    image: memcached
    ports:
        - "11211"
    volumes:
      - ./:/var/www
    networks:
      - short_net

  phpmyadmin:
    image: phpmyadmin
    container_name: short-phpmyadmin
    ports:
      - 8001:80
    environment:
      PMA_HOST: db
      PMA_USER: ${DB_USERNAME}
      PMA_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db
    networks:
      - short_net

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui
    networks:
      - short_net

networks:
  short_net:
    driver: bridge
